"""HtmlRenderer tests."""

from __future__ import annotations

from coupling_core import RepoAnalysis

from churnmap.config import ChurnmapConfig
from churnmap.data_preparer import DataPreparer
from churnmap.html_renderer import HtmlRenderer


def test_rendered_html_contains_d3_cdn_script(sample_analysis: RepoAnalysis) -> None:
    html = _render(sample_analysis)

    assert '<script src="https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js"></script>' in html


def test_rendered_html_title_contains_repo_name(sample_analysis: RepoAnalysis) -> None:
    html = _render(sample_analysis)

    assert "<title>ChurnMap — Meru143/churnmap</title>" in html


def test_rendered_html_contains_tab_buttons(sample_analysis: RepoAnalysis) -> None:
    html = _render(sample_analysis)

    assert "Heatmap" in html
    assert "Force Graph" in html
    assert "Table" in html


def test_rendered_html_contains_d3_cdn_comment(sample_analysis: RepoAnalysis) -> None:
    html = _render(sample_analysis)

    assert "<!-- D3.js loaded from CDN" in html


def test_rendered_html_is_full_html_document(sample_analysis: RepoAnalysis) -> None:
    html = _render(sample_analysis)

    assert html.startswith("<!DOCTYPE html>")
    assert html.rstrip().endswith("</html>")


def test_footer_contains_churnmap_version(sample_analysis: RepoAnalysis) -> None:
    html = _render(sample_analysis)

    assert "Generated by churnmap v1.0.0" in html


def test_rendered_html_contains_embedded_heatmap_json(sample_analysis: RepoAnalysis) -> None:
    html = _render(sample_analysis)

    assert "const heatmapFiles = " in html
    assert '"src/payment.py"' in html


def _render(analysis: RepoAnalysis) -> str:
    report = DataPreparer(ChurnmapConfig()).prepare(analysis)
    return HtmlRenderer().render(report)
